export const rows = [
  {
    id: 1,
    RegisterID: "123512",
    name: "Jon",
    age: 35,
    phone: "(110)659-4212",
    email: "Snow@gmail.com",
    address: "UK",
    city: "Liverpool",
    zipCode: "10001",
  },
  {
    id: 2,
    RegisterID: "123512",
    name: "Cersei",
    age: 42,
    phone: "(484)598-8742",
    email: "Lannister@gmail.com",
    address: "Egypt",
    city: "Cairo",
    zipCode: "87281",
  },
  {
    id: 3,
    RegisterID: "413252",
    name: "Jaime",
    age: 45,
    phone: "(639)520-6980",
    email: "Lannister@gmail.com",
    address: "Italy",
    city: "Rome",
    zipCode: "87281",
  },
  {
    id: 4,
    RegisterID: "123512",
    name: "Arya",
    age: 16,
    phone: "(956)633-8759",
    email: "Stark@gmail.com",
    address: "UK",
    city: "Manchester",
    zipCode: "15551",
  },
  {
    id: 5,
    RegisterID: "123512",
    name: "Daenerys",
    age: 30,
    phone: "(963)690-8742",
    email: "Targaryen@gmail.com",
    address: "UK",
    city: "Everton",
    zipCode: "14215",
  },
  {
    id: 6,
    RegisterID: "123512",
    name: "Freya",
    age: 150,
    phone: "(350)597-0058",
    email: "Melisandre@gmail.com",
    address: "US",
    city: "New York",
    zipCode: "10001",
  },
  {
    id: 7,
    RegisterID: "123512",
    name: "Ferrara",
    age: 44,
    phone: "(264)953-2604",
    email: "Clifford@gmail.com",
    address: "Egypt",
    city: "Tnata",
    zipCode: "51523",
  },
  {
    id: 8,
    RegisterID: "123512",
    name: "Rossini",
    age: 36,
    phone: "(789)687-1298",
    email: "Frances@gmail.com",
    address: "Italy",
    city: "Milan",
    zipCode: "44215",
  },
  {
    id: 9,
    RegisterID: "928397",
    name: "Harvey",
    age: 65,
    phone: "(684)489-2658",
    email: "Roxie@gmail.com",
    address: "Italy",
    city: "Milan",
    zipCode: "11123",
  },
  {
    id: 10,
    RegisterID: "512315",
    name: "Abdelrhman",
    age: 65,
    phone: "(011)567-2173",
    email: "abdoelsayed293@gmail.com",
    address: "Egypt",
    city: "Tanta",
    zipCode: "44215",
  },
];

export const columns = [
  {
    field: "id",
    headerName: "ID",
    width: 33,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "RegisterID",
    headerName: "RegisterID",
    align: "center",
    width: 140,
    headerAlign: "center",
  },
  {
    field: "name",
    headerName: "Name",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "email",
    headerName: "Email",
    width: 130,
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "age",
    headerName: "Age",
    type: "number",
    width: 90,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "phone",
    headerName: "Phone",
    sortable: true,
    width: 160,
    flex: 1,
    align: "center",
    headerAlign: "center",
  },

  {
    field: "address",
    headerName: "Address",
    align: "center",
    width: 140,
    headerAlign: "center",
  },
  {
    field: "city",
    headerName: "City",
    align: "center",
    width: 140,
    headerAlign: "center",
  },
  {
    field: "zipCode",
    headerName: "Zip Code",
    align: "center",
    width: 140,
    headerAlign: "center",
  },
];
